package com.kylekewley.piclient.protocolbuffers;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupRegistration.proto

public final class GroupRegistrationProto {
  private GroupRegistrationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GroupRegistrationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string groupID = 1;
    /**
     * <code>required string groupID = 1;</code>
     *
     * <pre>
     *The group to add/remove from 
     * </pre>
     */
    boolean hasGroupID();
    /**
     * <code>required string groupID = 1;</code>
     *
     * <pre>
     *The group to add/remove from 
     * </pre>
     */
    java.lang.String getGroupID();
    /**
     * <code>required string groupID = 1;</code>
     *
     * <pre>
     *The group to add/remove from 
     * </pre>
     */
    com.google.protobuf.ByteString
        getGroupIDBytes();

    // required bool addToGroup = 2;
    /**
     * <code>required bool addToGroup = 2;</code>
     *
     * <pre>
     *True means add to group, False means remove from group
     * </pre>
     */
    boolean hasAddToGroup();
    /**
     * <code>required bool addToGroup = 2;</code>
     *
     * <pre>
     *True means add to group, False means remove from group
     * </pre>
     */
    boolean getAddToGroup();

    // optional uint32 flags = 3;
    /**
     * <code>optional uint32 flags = 3;</code>
     *
     * <pre>
     *Can be used to determine what priority message gets sent to us
     * </pre>
     */
    boolean hasFlags();
    /**
     * <code>optional uint32 flags = 3;</code>
     *
     * <pre>
     *Can be used to determine what priority message gets sent to us
     * </pre>
     */
    int getFlags();

    // optional string clientName = 4;
    /**
     * <code>optional string clientName = 4;</code>
     *
     * <pre>
     *Can be used to identify the client
     * </pre>
     */
    boolean hasClientName();
    /**
     * <code>optional string clientName = 4;</code>
     *
     * <pre>
     *Can be used to identify the client
     * </pre>
     */
    java.lang.String getClientName();
    /**
     * <code>optional string clientName = 4;</code>
     *
     * <pre>
     *Can be used to identify the client
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientNameBytes();
  }
  /**
   * Protobuf type {@code GroupRegistration}
   */
  public static final class GroupRegistration extends
      com.google.protobuf.GeneratedMessageLite
      implements GroupRegistrationOrBuilder {
    // Use GroupRegistration.newBuilder() to construct.
    private GroupRegistration(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private GroupRegistration(boolean noInit) {}

    private static final GroupRegistration defaultInstance;
    public static GroupRegistration getDefaultInstance() {
      return defaultInstance;
    }

    public GroupRegistration getDefaultInstanceForType() {
      return defaultInstance;
    }

    private GroupRegistration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              groupID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              addToGroup_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              flags_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              clientName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<GroupRegistration> PARSER =
        new com.google.protobuf.AbstractParser<GroupRegistration>() {
      public GroupRegistration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupRegistration(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupRegistration> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string groupID = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private java.lang.Object groupID_;
    /**
     * <code>required string groupID = 1;</code>
     *
     * <pre>
     *The group to add/remove from 
     * </pre>
     */
    public boolean hasGroupID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string groupID = 1;</code>
     *
     * <pre>
     *The group to add/remove from 
     * </pre>
     */
    public java.lang.String getGroupID() {
      java.lang.Object ref = groupID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string groupID = 1;</code>
     *
     * <pre>
     *The group to add/remove from 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGroupIDBytes() {
      java.lang.Object ref = groupID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool addToGroup = 2;
    public static final int ADDTOGROUP_FIELD_NUMBER = 2;
    private boolean addToGroup_;
    /**
     * <code>required bool addToGroup = 2;</code>
     *
     * <pre>
     *True means add to group, False means remove from group
     * </pre>
     */
    public boolean hasAddToGroup() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool addToGroup = 2;</code>
     *
     * <pre>
     *True means add to group, False means remove from group
     * </pre>
     */
    public boolean getAddToGroup() {
      return addToGroup_;
    }

    // optional uint32 flags = 3;
    public static final int FLAGS_FIELD_NUMBER = 3;
    private int flags_;
    /**
     * <code>optional uint32 flags = 3;</code>
     *
     * <pre>
     *Can be used to determine what priority message gets sent to us
     * </pre>
     */
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 flags = 3;</code>
     *
     * <pre>
     *Can be used to determine what priority message gets sent to us
     * </pre>
     */
    public int getFlags() {
      return flags_;
    }

    // optional string clientName = 4;
    public static final int CLIENTNAME_FIELD_NUMBER = 4;
    private java.lang.Object clientName_;
    /**
     * <code>optional string clientName = 4;</code>
     *
     * <pre>
     *Can be used to identify the client
     * </pre>
     */
    public boolean hasClientName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string clientName = 4;</code>
     *
     * <pre>
     *Can be used to identify the client
     * </pre>
     */
    public java.lang.String getClientName() {
      java.lang.Object ref = clientName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientName = 4;</code>
     *
     * <pre>
     *Can be used to identify the client
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      java.lang.Object ref = clientName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      groupID_ = "";
      addToGroup_ = false;
      flags_ = 0;
      clientName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGroupID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddToGroup()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, addToGroup_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, flags_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getClientNameBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, addToGroup_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, flags_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getClientNameBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GroupRegistrationProto.GroupRegistration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GroupRegistrationProto.GroupRegistration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GroupRegistrationProto.GroupRegistration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GroupRegistrationProto.GroupRegistration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GroupRegistrationProto.GroupRegistration prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code GroupRegistration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          GroupRegistrationProto.GroupRegistration, Builder>
        implements GroupRegistrationProto.GroupRegistrationOrBuilder {
      // Construct using com.kylekewley.piclient.protocolbuffers.GroupRegistrationProto.GroupRegistration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        addToGroup_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public GroupRegistrationProto.GroupRegistration getDefaultInstanceForType() {
        return GroupRegistrationProto.GroupRegistration.getDefaultInstance();
      }

      public GroupRegistrationProto.GroupRegistration build() {
        GroupRegistrationProto.GroupRegistration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GroupRegistrationProto.GroupRegistration buildPartial() {
        GroupRegistrationProto.GroupRegistration result = new GroupRegistrationProto.GroupRegistration(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupID_ = groupID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.addToGroup_ = addToGroup_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientName_ = clientName_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(GroupRegistrationProto.GroupRegistration other) {
        if (other == GroupRegistrationProto.GroupRegistration.getDefaultInstance()) return this;
        if (other.hasGroupID()) {
          bitField0_ |= 0x00000001;
          groupID_ = other.groupID_;
          
        }
        if (other.hasAddToGroup()) {
          setAddToGroup(other.getAddToGroup());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasClientName()) {
          bitField0_ |= 0x00000008;
          clientName_ = other.clientName_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupID()) {
          
          return false;
        }
        if (!hasAddToGroup()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GroupRegistrationProto.GroupRegistration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GroupRegistrationProto.GroupRegistration) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string groupID = 1;
      private java.lang.Object groupID_ = "";
      /**
       * <code>required string groupID = 1;</code>
       *
       * <pre>
       *The group to add/remove from 
       * </pre>
       */
      public boolean hasGroupID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string groupID = 1;</code>
       *
       * <pre>
       *The group to add/remove from 
       * </pre>
       */
      public java.lang.String getGroupID() {
        java.lang.Object ref = groupID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string groupID = 1;</code>
       *
       * <pre>
       *The group to add/remove from 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGroupIDBytes() {
        java.lang.Object ref = groupID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string groupID = 1;</code>
       *
       * <pre>
       *The group to add/remove from 
       * </pre>
       */
      public Builder setGroupID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupID_ = value;
        
        return this;
      }
      /**
       * <code>required string groupID = 1;</code>
       *
       * <pre>
       *The group to add/remove from 
       * </pre>
       */
      public Builder clearGroupID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupID_ = getDefaultInstance().getGroupID();
        
        return this;
      }
      /**
       * <code>required string groupID = 1;</code>
       *
       * <pre>
       *The group to add/remove from 
       * </pre>
       */
      public Builder setGroupIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupID_ = value;
        
        return this;
      }

      // required bool addToGroup = 2;
      private boolean addToGroup_ ;
      /**
       * <code>required bool addToGroup = 2;</code>
       *
       * <pre>
       *True means add to group, False means remove from group
       * </pre>
       */
      public boolean hasAddToGroup() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool addToGroup = 2;</code>
       *
       * <pre>
       *True means add to group, False means remove from group
       * </pre>
       */
      public boolean getAddToGroup() {
        return addToGroup_;
      }
      /**
       * <code>required bool addToGroup = 2;</code>
       *
       * <pre>
       *True means add to group, False means remove from group
       * </pre>
       */
      public Builder setAddToGroup(boolean value) {
        bitField0_ |= 0x00000002;
        addToGroup_ = value;
        
        return this;
      }
      /**
       * <code>required bool addToGroup = 2;</code>
       *
       * <pre>
       *True means add to group, False means remove from group
       * </pre>
       */
      public Builder clearAddToGroup() {
        bitField0_ = (bitField0_ & ~0x00000002);
        addToGroup_ = false;
        
        return this;
      }

      // optional uint32 flags = 3;
      private int flags_ ;
      /**
       * <code>optional uint32 flags = 3;</code>
       *
       * <pre>
       *Can be used to determine what priority message gets sent to us
       * </pre>
       */
      public boolean hasFlags() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 flags = 3;</code>
       *
       * <pre>
       *Can be used to determine what priority message gets sent to us
       * </pre>
       */
      public int getFlags() {
        return flags_;
      }
      /**
       * <code>optional uint32 flags = 3;</code>
       *
       * <pre>
       *Can be used to determine what priority message gets sent to us
       * </pre>
       */
      public Builder setFlags(int value) {
        bitField0_ |= 0x00000004;
        flags_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 flags = 3;</code>
       *
       * <pre>
       *Can be used to determine what priority message gets sent to us
       * </pre>
       */
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00000004);
        flags_ = 0;
        
        return this;
      }

      // optional string clientName = 4;
      private java.lang.Object clientName_ = "";
      /**
       * <code>optional string clientName = 4;</code>
       *
       * <pre>
       *Can be used to identify the client
       * </pre>
       */
      public boolean hasClientName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string clientName = 4;</code>
       *
       * <pre>
       *Can be used to identify the client
       * </pre>
       */
      public java.lang.String getClientName() {
        java.lang.Object ref = clientName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientName = 4;</code>
       *
       * <pre>
       *Can be used to identify the client
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientNameBytes() {
        java.lang.Object ref = clientName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientName = 4;</code>
       *
       * <pre>
       *Can be used to identify the client
       * </pre>
       */
      public Builder setClientName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientName_ = value;
        
        return this;
      }
      /**
       * <code>optional string clientName = 4;</code>
       *
       * <pre>
       *Can be used to identify the client
       * </pre>
       */
      public Builder clearClientName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientName_ = getDefaultInstance().getClientName();
        
        return this;
      }
      /**
       * <code>optional string clientName = 4;</code>
       *
       * <pre>
       *Can be used to identify the client
       * </pre>
       */
      public Builder setClientNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientName_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GroupRegistration)
    }

    static {
      defaultInstance = new GroupRegistration(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GroupRegistration)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
